name: Compile Examples

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [ "esp8266:esp8266:nodemcuv2", "esp32:esp32:esp32" ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Install Cores
        run: |
          # Langsung update index dengan menyertakan URL (Tanpa simpan di config dulu biar gak error)
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://espressif.github.io/arduino-esp32/package_esp32_index.json
          
          # Install core menggunakan URL yang sama
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

      - name: Install Libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          # Clone library NTP pendukung
          git clone https://github.com/iskakfatoni/IskakINO_FastNTP.git $HOME/Arduino/libraries/IskakINO_FastNTP
          # Link library utama kamu
          ln -s $GITHUB_WORKSPACE $HOME/Arduino/libraries/IskakINO_WifiPortal

      - name: Compile Examples
        run: |
          for example in $(find examples -name "*.ino"); do
            echo "Compiling $example..."
            arduino-cli compile --fqbn ${{ matrix.board }} "$example" --libraries $HOME/Arduino/libraries
          done
