name: Compile Examples

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [ "esp8266:esp8266:nodemcuv2", "esp32:esp32:esp32" ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Configure Arduino CLI & Core
        run: |
          # Inisialisasi konfigurasi
          arduino-cli config init
          
          # UPDATE URL DISINI: Menggunakan URL resmi terbaru dari Espressif
          arduino-cli config set board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json
          
          # Update index board manager
          arduino-cli core update-index
          
          # Install core board
          arduino-cli core install esp8266:esp8266
          arduino-cli core install esp32:esp32

      - name: Install Dependencies & External Libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          
          # Clone Library NTP kamu
          git clone https://github.com/iskakfatoni/IskakINO_FastNTP.git $HOME/Arduino/libraries/IskakINO_FastNTP
          
          # Link library utama IskakINO_WifiPortal
          ln -s $GITHUB_WORKSPACE $HOME/Arduino/libraries/IskakINO_WifiPortal

      - name: Compile Examples
        run: |
          for example in $(find examples -name "*.ino"); do
            echo "-------------------------------------------------------"
            echo "Compiling $example for ${{ matrix.board }}..."
            echo "-------------------------------------------------------"
            arduino-cli compile --fqbn ${{ matrix.board }} "$example" --libraries $HOME/Arduino/libraries
          done
